In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [3]:
df=pd.read_csv("Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# dropping irrelevant features
df=df.drop(["RowNumber","CustomerId","Surname"],axis=1)
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [5]:
df["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [38]:
# encoding categorical variables
label_encoder=LabelEncoder()
df["Gender"]=label_encoder.fit_transform(df["Gender"])
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [39]:
# one hot encodeing geography column
one_hot_encoder=OneHotEncoder()
geo_encoded=one_hot_encoder.fit_transform(df[["Geography"]])

In [40]:
geo_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [41]:
one_hot_encoder.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [42]:
geo_encoded_df=pd.DataFrame(geo_encoded.toarray(),columns=one_hot_encoder.get_feature_names_out())
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [43]:
data=pd.concat([geo_encoded_df,df.drop("Geography",axis=1)],axis=1)
data.head()

Geography_France  Geography_Germany  Geography_Spain  CreditScore  Gender  \
0               1.0                0.0              0.0          619       0   
1               0.0                0.0              1.0          608       0   
2               1.0                0.0              0.0          502       0   
3               1.0                0.0              0.0          699       0   
4               0.0                0.0              1.0          850       0   

   Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0   42       2       0.00              1          1               1   
1   41       1   83807.86              1          0               1   
2   42       8  159660.80              3          1               0   
3   39       1       0.00              2          0               0   
4   43       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [45]:
# diving dataset into dependent and independent features
x=data.drop("Exited",axis=1)
y=data["Exited"]

# splitting the dataset
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# scaling the features
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)


In [46]:
x_train[:,:6]

array([[ 1.00150113, -0.57946723, -0.57638802,  0.35649971,  0.91324755,
        -0.6557859 ],
       [-0.99850112,  1.72572313, -0.57638802, -0.20389777,  0.91324755,
         0.29493847],
       [-0.99850112, -0.57946723,  1.73494238, -0.96147213,  0.91324755,
        -1.41636539],
       ...,
       [ 1.00150113, -0.57946723, -0.57638802,  0.86500853, -1.09499335,
        -0.08535128],
       [ 1.00150113, -0.57946723, -0.57638802,  0.15932282,  0.91324755,
         0.3900109 ],
       [-0.99850112,  1.72572313, -0.57638802,  0.47065475,  0.91324755,
         1.15059039]], shape=(8000, 6))

In [33]:
(x_train.shape[1],)

(12,)

# ANN Implementation

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import datetime

ImportError: Traceback (most recent call last):
  File "c:\Users\aswin\Music\space\ANN Classification\venv\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 73, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

In [44]:
# Building our ANN model
model=Sequential([
    Dense(64,activation="relu",input_shape=(x_train.shape[1],)),   #HL1 connected with input layer
    Dense(32,activation="relu"),   #HL2
    Dense(1,activation="sigmoid")  #output layer
])

c:\Users\aswin\Music\space\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [45]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [47]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [48]:
# compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=["accuracy"])   # values can be given as both optimizer value and loss in this

In [50]:
# set up Early Stopping
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=5,restore_best_weights=True)

In [ ]:
# Train the model
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.8254 - loss: 0.4110 - val_accuracy: 0.8530 - val_loss: 0.3446
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8553 - loss: 0.3558 - val_accuracy: 0.8540 - val_loss: 0.3459
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8575 - loss: 0.3498 - val_accuracy: 0.8540 - val_loss: 0.3414
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8594 - loss: 0.3402 - val_accuracy: 0.8570 - val_loss: 0.3619
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8609 - loss: 0.3392 - val_accuracy: 0.8565 - val_loss: 0.3471
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8614 - loss: 0.3384 - val_accuracy: 0.8595 - val_loss: 0.3402
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8640 - loss: 0.3323 - val_accuracy: 0.8525 - val_loss: 0.3502
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8621 - loss: 0.3333 - val_

In [ ]:
# Example input data
input_data={
    "CreditScore":600,
    "Geography":"France",
    "Gender":"Male",
    "Age":40,
    "Tenure":3,
    "Balance":60000,
    "NumOfProducts":2,
    "HasCrCard":1,
    "IsActiveMember":1,
    "EstimatedSalary":50000
}

In [72]:
geo_encoded=one_hot_encoder.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder.get_feature_names_out())
geo_encoded_df

c:\Users\aswin\Music\space\ANN Classification\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [73]:
input_data=pd.DataFrame([input_data])
input_data

CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [78]:
input_df=pd.concat([geo_encoded_df,input_data.drop("Geography",axis=1)],axis=1)
input_df

Geography_France  Geography_Germany  ...  IsActiveMember  EstimatedSalary
0               1.0                0.0  ...               1            50000

[1 rows x 12 columns]

In [79]:
input_df["Gender"]=label_encoder.transform(input_df["Gender"])
input_df

Geography_France  Geography_Germany  ...  IsActiveMember  EstimatedSalary
0               1.0                0.0  ...               1            50000

[1 rows x 12 columns]

In [80]:
input_scaled=scaler.transform(input_df)
input_scaled

array([[ 1.00150113, -0.57946723, -0.57638802, -0.53598516,  0.91324755,
         0.10479359, -0.69539349, -0.25781119,  0.80843615,  0.64920267,
         0.97481699, -0.87683221]])

In [84]:
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 292ms/step


array([[0.03208745]], dtype=float32)

In [88]:
prediction_proba=prediction[0][0]
prediction_proba

np.float32(0.032087453)

In [89]:
if prediction_proba>0.5:
    print("The customer is likely to churn")
else:
    print("The customer is not likely to churn")

The customer is not likely to churn
